### ISSUE TITLE
TypeError: 'NoneType' object is not callable when doing session.add

### ISSUE THREAD

**Issue by gbgmian** [siddhantgoel/tornado-sqlalchemy#12]
From a Tornado handler defined as @coroutine it works fine with a simple count-query as in example, but when only changing to do a session.add instead (insert) I get a TypeError on the session.add-row. MyOrder is a vanilla SQLAlchemy model.

```python
new_obj = MyOrder(id=123, sym="test", type="blabl")

with self.make_session() as session:
      yield as_future(session.add(new_obj))
```

Am I supposed to add objects in some other way or is it a bug in tornado-sqlalchemy?

**Comment by siddhantgoel** [comment]
[`session.add`](http://docs.sqlalchemy.org/en/latest/orm/session_api.html#sqlalchemy.orm.session.Session.add) does not return a callable. [`session.query`](http://docs.sqlalchemy.org/en/latest/orm/session_api.html#sqlalchemy.orm.session.Session.query) on the other hand returns a Query object, which you can call, and which makes `as_future` happy because it's expecting a function.

Inserts are usually quick, so you don't necessarily have to background them. The normal `session.add` without `as_future` should work.

```python
new_obj = MyOrder(id=123, sym="test", type="blabl")

with self.make_session() as session:
      session.add(new_obj))
```

In fact, I just updated one of the test cases to include an insert in this commit - https://github.com/siddhantgoel/tornado-sqlalchemy/commit/8cb314d507bcc94ae33bd9ea9078850d75cfbdf0 .

**Comment by siddhantgoel** [comment]
@gbgmian I just closed this issue, but feel free to reopen if you have follow-up questions.

**Comment by gbgmian** [comment]
Thanks a lot for quick help!
