### ISSUE TITLE
Tornado V5.0

### ISSUE THREAD

**Issue by mgcdanny** [siddhantgoel/tornado-sqlalchemy#7]
Hi,

I've been having a great time using this package.

I notice Tornado V5.0 was recently releases and it is moving towards the asyncio compatability.

Specifically:

"On Python 3, the IOLoop is always a wrapper around the asyncio event loop, and asyncio.Future and asyncio.Task are used instead of their Tornado counterparts. This means that libraries based on asyncio can be mixed relatively seamlessly with those using Tornado. While care has been taken to minimize the disruption from this change, code changes may be required for compatibility with Tornado 5.0, as detailed in the following section."

I am wondering if this will conflict with this packages async behavior per docs:

"...please note that currently we don’t support the native asyncio.Future objects included in Python 3. So if your request handlers are async def-ed, then calling await on the future that as_future returns would likely not work. But the good news is that a later version of this library should support this use case as well."

http://www.tornadoweb.org/en/stable/releases/v5.0.0.html

**Comment by siddhantgoel** [comment]
Hey @mgcdanny , supporting the native async/adef style coroutines would *probably* mean dropping Python 2.7 compatibility, which is why they haven't been implemented yet. Plus, I'm not familiar with the exact details of the async/adef protocol, so I can't guarantee that it would work, but you're welcome to try it out!

That being said, I have this and a few other features in mind which might make for a good next release, so thanks for bringing this into attention.

I'll look into supporting the native Python 3+ coroutines in the coming few weeks.

**Comment by mgcdanny** [comment]
fyi:

"Python 2.7 and 3.4 are deprecated and support for them will be removed in Tornado 6.0, which will require Python 3.5+."

Thanks

**Comment by siddhantgoel** [comment]
Update:

I'm working on this in the [native-coroutines](https://github.com/siddhantgoel/tornado-sqlalchemy/tree/native-coroutines) branch. The whole thing is a bit confusing, since `concurrent.futures.Future` coroutines are not `await`-able, and I'm not sure why this incompatibility exists (or was introduced) in the first place.

Anyway, the additional tests seem to pass, so this would likely be included in the next release.

**Comment by siddhantgoel** [comment]
Also, support for Python 2.7 and 3.4 would be removed as a result of this change. :man_shrugging:

**Comment by siddhantgoel** [comment]
Just pushed `0.5.0` which makes `future`s returned by `as_future` `await`able.
